/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Horse = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
});
export const CareActivity = IDL.Record({
  'id' : IDL.Nat,
  'horseId' : IDL.Nat,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'careType' : IDL.Text,
});
export const FeedingEvent = IDL.Record({
  'id' : IDL.Nat,
  'horseId' : IDL.Nat,
  'feedType' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Int,
});
export const Injury = IDL.Record({
  'id' : IDL.Nat,
  'horseId' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MedicineDosage = IDL.Record({
  'id' : IDL.Nat,
  'dosage' : IDL.Int,
  'horseId' : IDL.Nat,
  'unit' : IDL.Text,
  'medicine' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addHorse' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
  'deleteHorse' : IDL.Func([IDL.Nat], [], []),
  'getAllHorses' : IDL.Func([], [IDL.Vec(Horse)], ['query']),
  'getCareActivitiesForHorse' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CareActivity)],
      ['query'],
    ),
  'getHorse' : IDL.Func([IDL.Nat], [Horse], ['query']),
  'getHorseFeedingEvents' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FeedingEvent)],
      ['query'],
    ),
  'getHorseInjuries' : IDL.Func([IDL.Nat], [IDL.Vec(Injury)], ['query']),
  'getHorseMedicineDosages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MedicineDosage)],
      ['query'],
    ),
  'logCareActivity' : IDL.Func([IDL.Nat, IDL.Text], [CareActivity], []),
  'logFeedingEvent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [IDL.Nat], []),
  'logInjury' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'recordMedicineDosage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Horse = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
  });
  const CareActivity = IDL.Record({
    'id' : IDL.Nat,
    'horseId' : IDL.Nat,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'careType' : IDL.Text,
  });
  const FeedingEvent = IDL.Record({
    'id' : IDL.Nat,
    'horseId' : IDL.Nat,
    'feedType' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Int,
  });
  const Injury = IDL.Record({
    'id' : IDL.Nat,
    'horseId' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MedicineDosage = IDL.Record({
    'id' : IDL.Nat,
    'dosage' : IDL.Int,
    'horseId' : IDL.Nat,
    'unit' : IDL.Text,
    'medicine' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addHorse' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
    'deleteHorse' : IDL.Func([IDL.Nat], [], []),
    'getAllHorses' : IDL.Func([], [IDL.Vec(Horse)], ['query']),
    'getCareActivitiesForHorse' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CareActivity)],
        ['query'],
      ),
    'getHorse' : IDL.Func([IDL.Nat], [Horse], ['query']),
    'getHorseFeedingEvents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FeedingEvent)],
        ['query'],
      ),
    'getHorseInjuries' : IDL.Func([IDL.Nat], [IDL.Vec(Injury)], ['query']),
    'getHorseMedicineDosages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MedicineDosage)],
        ['query'],
      ),
    'logCareActivity' : IDL.Func([IDL.Nat, IDL.Text], [CareActivity], []),
    'logFeedingEvent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [IDL.Nat], []),
    'logInjury' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'recordMedicineDosage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };